import { css } from "styled-system/css";

// Shared Studio surfaces for the homepage and site chrome.
const width = {
	width: "full",
	maxWidth: "1200px",
	mx: "auto",
	px: { base: "5", md: "9" },
};

export const studio = {
	brandDot: css({ color: "yellow.300" }),
	site: css({
		isolation: "isolate",
		minHeight: "100vh",
		bg: "neutral.950",
		color: "neutral.100",
		fontSmoothing: "antialiased",
		fontOpticalSizing: "auto",
		"& :where(a, button, summary):focus-visible": {
			outline: "2px solid {colors.yellow.300}",
			outlineOffset: "5px",
		},
	}),
	nav: css({
		position: "sticky",
		top: "0",
		zIndex: "50",
		bg: "transparent",
		"&[data-scrolled]": {
			bg: "neutral.950/85",
			backdropFilter: "blur(20px) saturate(1.4)",
			"@media (prefers-reduced-transparency: reduce), (prefers-contrast: more)":
				{
					bg: "neutral.950",
					backdropFilter: "none",
				},
		},
	}),
	navInner: css({
		...width,
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		flexWrap: "wrap",
		gap: "3",
		py: "4",
		minHeight: "76px",
	}),
	wordmark: css({
		fontSize: "17px",
		fontWeight: "650",
		letterSpacing: "-0.6px",
		whiteSpace: "nowrap",
		"& span": { color: "yellow.300" },
	}),
	navLinks: css({
		display: "flex",
		alignItems: "center",
		gap: { base: "5", md: "8" },
		fontSize: "13px",
		fontWeight: "500",
		"& a": {
			py: "2",
			_hover: { textDecoration: "underline", textUnderlineOffset: "4px" },
		},
	}),
	hero: css({
		...width,
		display: "grid",
		gridTemplateColumns: { base: "1fr", md: "1.1fr 1fr" },
		alignItems: "center",
		gap: { base: "9", md: "8", lg: "18" },
		pt: { base: "10", md: "16" },
		pb: { base: "14", md: "20" },
	}),
	portraitFrame: css({
		position: "relative",
		width: "full",
		maxWidth: "480px",
		borderRadius: "24px",
		mx: "auto",
		_after: {
			content: '""',
			position: "absolute",
			inset: "0",
			borderRadius: "inherit",
			border: "1px solid rgba(255, 255, 255, 0.18)",
			pointerEvents: "none",
		},
	}),
	portrait: css({
		display: "block",
		width: "full",
		height: { base: "410px", md: "480px", lg: "530px" },
		objectFit: "cover",
		objectPosition: "53% center",
		borderRadius: "inherit",
	}),
	heroTitle: css({
		fontSize: {
			base: "clamp(2.5rem, 8vw, 3rem)",
			md: "clamp(2.5rem, 4.8vw, 4.125rem)",
		},
		fontWeight: "600",
		letterSpacing: "-0.05em",
		lineHeight: "1.05",
		"& span": { color: "neutral.400" },
	}),
	intro: css({
		color: "neutral.400",
		fontSize: "17px",
		lineHeight: "1.6",
		letterSpacing: "-0.3px",
		maxWidth: "390px",
		mt: "7",
		"& br": { display: "none" },
	}),
	heroActions: css({
		display: "flex",
		alignItems: "center",
		flexWrap: "wrap",
		gap: { base: "5", md: "7" },
		mt: "7",
	}),
	primaryLink: css({
		display: "inline-flex",
		alignItems: "center",
		gap: "5",
		borderRadius: "full",
		px: "6",
		py: "3.5",
		fontSize: "14px",
		fontWeight: "550",
		bg: "yellow.300",
		color: "neutral.900",
		_hover: { bg: "#ffe76a" },
		_active: { transform: "scale(0.97)" },
	}),
	textLink: css({
		display: "inline-block",
		fontSize: "14px",
		fontWeight: "500",
		py: "2.5",
		_hover: { textDecoration: "underline", textUnderlineOffset: "4px" },
	}),
	section: css({
		...width,
		scrollMarginTop: { base: "128px", sm: "100px" },
		pb: { base: "14", md: "20" },
	}),
	sectionHeading: css({
		display: "flex",
		alignItems: "end",
		justifyContent: "space-between",
		flexWrap: "wrap",
		gap: "3",
		mb: "8",
		"& h2": {
			fontSize: { base: "30px", md: "36px" },
			fontWeight: "600",
			letterSpacing: "-1.2px",
			lineHeight: "1.2",
		},
		"& p": { fontSize: "15px", color: "neutral.400", mt: "2" },
	}),
	grid: css({
		display: "grid",
		gridTemplateColumns: { base: "1fr", md: "repeat(2, minmax(0, 1fr))" },
		gap: "6",
	}),
	card: css({
		display: "flex",
		flexDirection: "column",
		minWidth: "0",
		borderRadius: { base: "20px", md: "26px" },
		border: "1px solid {colors.neutral.700/70}",
		bg: "neutral.900",
		px: { base: "6", md: "9" },
		pt: { base: "7", md: "9" },
		"&[data-featured]": {
			gridColumn: "1 / -1",
			px: { base: "6", md: "12" },
			pt: { base: "7", md: "10" },
			bg: "radial-gradient(ellipse at 90% 5%, #33312a, transparent 65%), #171717",
		},
	}),
	cardTitle: css({
		fontSize: { base: "28px", md: "36px" },
		fontWeight: "600",
		letterSpacing: "-1px",
		lineHeight: "1.15",
	}),
	cardDescription: css({
		fontSize: "15px",
		color: "neutral.400",
		lineHeight: "1.7",
		mt: "4",
		maxWidth: "640px",
	}),
	technologies: css({
		fontSize: "11px",
		color: "neutral.400",
		letterSpacing: "0.3px",
		mt: "3",
	}),
	cardLinks: css({
		display: "flex",
		flexWrap: "wrap",
		gap: "5",
		mt: "3",
		mb: "5",
	}),
	cardImage: css({
		display: "block",
		width: "full",
		height: "auto",
		flexShrink: "0",
		borderRadius: "10px 10px 0 0",
		mt: "auto",
		border: "1px solid {colors.neutral.700}",
		borderBottom: "0",
		"&[data-featured]": {
			width: { base: "full", md: "88%" },
			mx: "auto",
			borderWidth: { base: "3px", md: "5px" },
			borderColor: "neutral.700",
			boxShadow: "0 20px 45px #0006",
		},
	}),
	note: css({
		textAlign: "center",
		px: "6",
		pb: { base: "16", md: "24" },
		"& h2": {
			fontSize: { base: "30px", md: "38px" },
			fontWeight: "600",
			letterSpacing: "-1.5px",
		},
		"& p": {
			color: "neutral.400",
			lineHeight: "1.6",
			maxWidth: "480px",
			mx: "auto",
			my: "5",
		},
	}),
	curiosityLogo: css({
		display: "block",
		mx: "auto",
		mb: "6",
		width: "66px",
		height: "66px",
	}),
	writing: css({ bg: "neutral.900", py: { base: "14", md: "20" } }),
	writingInner: css({ ...width }),
	linksGrid: css({
		display: "grid",
		gridTemplateColumns: {
			base: "1fr",
			sm: "repeat(2, minmax(0, 1fr))",
			lg: "repeat(5, minmax(0, 1fr))",
		},
		gap: "4",
	}),
	linkCard: css({
		display: "block",
		bg: "neutral.900",
		border: "1px solid {colors.neutral.700/70}",
		borderRadius: "20px",
		p: "6",
		"& h3": { fontSize: "17px", fontWeight: "600" },
		"& p": {
			fontSize: "13px",
			color: "neutral.400",
			mt: "3",
			overflowWrap: "anywhere",
		},
		_hover: {
			borderColor: "neutral.500",
			"& h3": { textDecoration: "underline", textUnderlineOffset: "4px" },
		},
	}),
	writingTitle: css({
		fontSize: "clamp(2rem, 4vw, 3.25rem)",
		fontWeight: "600",
		letterSpacing: "-1.8px",
		lineHeight: "1.1",
	}),
	writingCopy: css({
		color: "neutral.400",
		fontSize: "17px",
		lineHeight: "1.6",
		maxWidth: "480px",
		my: "4",
	}),
	postGrid: css({
		display: "grid",
		gridTemplateColumns: { base: "1fr", md: "repeat(3, minmax(0, 1fr))" },
		gap: "8",
		mt: "10",
		"& article": { borderTop: "1px solid {colors.neutral.700}", pt: "6" },
	}),
	footer: css({ bg: "neutral.900", pb: "10", scrollMarginTop: "100px" }),
	footerInner: css({ ...width }),
	footerRow: css({
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
		flexWrap: "wrap",
		gap: "5",
		borderTop: "1px solid {colors.neutral.700}",
		pt: "6",
		fontSize: "12px",
		color: "neutral.400",
		"& nav": { display: "flex", flexWrap: "wrap", gap: "6" },
		"& a": {
			py: "2",
			_hover: {
				color: "neutral.100",
				textDecoration: "underline",
				textUnderlineOffset: "4px",
			},
		},
	}),
};
